---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
        namespace: nginx-ingress
      interval: 12h
  values:
    controller:
      ingressClassResource:
        default: true
      watchIngressWithoutClass: true 